src/SimpleFeed.Web/Models/FeedViewModels/AddExternalLinkViewModel.cs
namespace SimpleFeed.Models.FeedViewModels
{
    using System.ComponentModel.DataAnnotations;

    public class AddExternalLinkViewModel : AddFeedEntryViewModel
    {
        [Required]
        [RegularExpression("^(https?)://[^\\s/$.?#].[^\\s]*$")]
        public string LinkAddress { get; set; }
    }


}

src/SimpleFeed.Web/Models/FeedViewModels/AddFeedEntryViewModel.cs
namespace SimpleFeed.Models.FeedViewModels
{
    using System.ComponentModel.DataAnnotations;

    public class AddFeedEntryViewModel
    {
        [Required]
        public string Title { get; set; }
        
        public string Description { get; set; }
    }
}

src/SimpleFeed.Web/Models/FeedViewModels/AddUploadedImageViewModel.cs
namespace SimpleFeed.Models.FeedViewModels
{
    using System.ComponentModel.DataAnnotations;
    using Microsoft.AspNetCore.Http;

    public class AddUploadedImageViewModel : AddFeedEntryViewModel
    {
        [Required]
        public IFormFile Image { get; set; }
    }
}

src/SimpleFeed.Web/Controllers/FeedController.cs
namespace SimpleFeed.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Base;
    using Core.FeedEntries;
    using Core.User;
    using Data.Commands.FeedEntries;
    using Data.OperationInputs;
    using Data.Queries;
    using Data.Storage;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using Models;
    using Models.FeedViewModels;
    using Services;
    using _Configuration;

    public class FeedController : BaseController
    {
        private readonly IWebScreenshotService _screenshotService;

        public FeedController(IOptions<PersistenceConfiguration> configuration, UserManager<ApplicationUser> userManager,
            IWebScreenshotService screenshotService)
            : base(configuration, userManager)
        {
            if (screenshotService == null) throw new ArgumentNullException(nameof(screenshotService));
            _screenshotService = screenshotService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var entries = new GetAllEntries(Configuration.Value)
            {
                PaginationRequest = new PaginationRequest(1, 10),
                DateCreatedOrder = DateCreatedOrder.Descending,
            }.Execute();

            return View(entries);
        }

        [HttpGet]
        public IActionResult TopTen()
        {
            var entries = new GetTopEntries(Configuration.Value)
            {
                HowMany = 10
            }.Execute();

            return View(entries);
        }

        [HttpGet]
        public IActionResult GetEntry(Guid entryId)
        {
            if (entryId.Equals(Guid.Empty)) return BadRequest();

            var entry = new GetEntryById(Configuration.Value)
            {
                EntryId = entryId
            }.Execute();

            return View(entry.Output);
        }

        [Authorize]
        [HttpGet]
        public IActionResult AddFeedEntryForm()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult AddExternalLinkForm()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddExternalLink(AddExternalLinkViewModel viewModel)
        {
            if (!ModelState.IsValid) return AjaxRequestFailure();

            var user = await UserManager.GetUserAsync(HttpContext.User);
            var command = new AddExternalLinkEntry(Configuration.Value)
            {
                ExternalLink = new ExternalLinkFeedEntry(new Uri(viewModel.LinkAddress), viewModel.Title, user.Id)
                {
                    Description = viewModel.Description
                }
            };
            var result = command.Execute();

            if (result.WasSuccessful)
            {
                var snapshotStorageCommand = new StoreUrlSnapshotImage(Configuration.Value)
                {
                    EntryId = command.ExternalLink.Id,
                    Image = await _screenshotService.GetScreenshotFor(command.ExternalLink.LinkAddress.AbsoluteUri),
                    UserId = user.Id
                };
                await snapshotStorageCommand.ExecuteAsync();
            }
            else
            {
                return AjaxRequestFailure(result.ValidationResult.ValidationMessage);
            }

            return new JsonResult(
                new AddExternalLinkResultViewModel
                {
                    EntryId = command.ExternalLink.Id,
                    Message = result.ValidationResult.ValidationMessage,
                    Success = result.WasSuccessful
                });
        }

        [Authorize]
        [HttpGet]
        public IActionResult AddUploadedImageForm()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUploadedImage(AddUploadedImageViewModel viewModel)
        {
            if (!ModelState.IsValid) return RedirectToAction(nameof(AddUploadedImageForm));

            var user = await UserManager.GetUserAsync(HttpContext.User);

            var uploadedFilePath = await new StoreUploadedFeedImage(Configuration.Value)
            {
                UserId = user.Id,
                Image = viewModel.Image
            }.ExecuteAsync();

            var command = new AddUploadedImageEntry(Configuration.Value)
            {
                UploadedImageEntry = new UploadedImageFeedEntry(uploadedFilePath, viewModel.Title, user.Id)
                {
                    Description = viewModel.Description
                }
            };
            var result = command.Execute();

            return !result.WasSuccessful
                ? RedirectToAction(nameof(AddUploadedImageForm))
                : RedirectToAction(nameof(GetEntry), new {entryId = command.UploadedImageEntry.Id});
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditFeedEntry(Guid entryId)
        {
            if (entryId.Equals(Guid.Empty)) return BadRequest();

            var entry = new GetEntryById(Configuration.Value)
            {
                EntryId = entryId
            }.Execute();

            var user = await UserManager.GetUserAsync(HttpContext.User);
            if (!entry.Output.Creator.Id.Equals(user.Id)) return Unauthorized();

            return View(entry.Output.Model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateFeedEntry(UpdateFeedEntryViewModel viewModel)
        {
            if (!ModelState.IsValid || viewModel.Id.Equals(Guid.Empty)) return RedirectToAction(nameof(Index));

            var user = await UserManager.GetUserAsync(HttpContext.User);
            var canUpdate = new CheckIfCanModifyEntry(Configuration.Value)
            {
                EntryId = viewModel.Id,
                UserId = user.Id
            }.Execute();
            if (!canUpdate.Output) return Unauthorized();

            var result = new UpdateFeedEntry(Configuration.Value)
            {
                UpdatedEntryId = viewModel.Id,
                NewTitle = viewModel.Title,
                NewDescription = viewModel.Description
            }.Execute();

            return RedirectToAction(nameof(GetEntry), new {entryId = viewModel.Id});
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> DeleteFeedEntry(Guid entryId)
        {
            if (entryId.Equals(Guid.Empty)) return BadRequest();

            var user = await UserManager.GetUserAsync(HttpContext.User);
            var canDelete = new CheckIfCanModifyEntry(Configuration.Value)
            {
                EntryId = entryId,
                UserId = user.Id
            }.Execute();
            if (!canDelete.Output) return Unauthorized();

            var result = new DeleteFeedEntry(Configuration.Value) {EntryId = entryId}.Execute();

            return RedirectToAction(nameof(Index));
        }
    }
}

src/SimpleFeed.Web/Controllers/UserController.cs
namespace SimpleFeed.Controllers
{
    using System;
    using Base;
    using Core.User;
    using Data.OperationInputs;
    using Data.Queries;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using _Configuration;

    public class UserController : BaseController
    {
        public UserController(IOptions<PersistenceConfiguration> configuration, UserManager<ApplicationUser> userManager)
            : base(configuration, userManager)
        {

        }

        [Authorize]
        public IActionResult Index()
        {
            var users = new GetAllUsers(Configuration.Value)
            {
                PaginationRequest = new PaginationRequest(1, 10)
            }.Execute();

            return View(users.Output);
        }

        [Authorize]
        public IActionResult GetUser(Guid userId)
        {
            var user = new GetUserWithActivity(Configuration.Value)
            {
                UserId = userId
            }.Execute();

            return View(user.Output);
        }
    }
}

src/SimpleFeed.Web/Controllers/VoteController.cs
namespace SimpleFeed.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Base;
    using Core.User;
    using Data.Commands.Interactions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using Models.VoteViewModels;
    using _Configuration;

    public class VoteController : BaseController
    {
        public VoteController(IOptions<PersistenceConfiguration> configuration, UserManager<ApplicationUser> userManager) 
            : base(configuration, userManager)
        {
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MakeVoteForFeedEntry(Guid votedEntryId, bool isUpvote)
        {
            if (votedEntryId.Equals(Guid.Empty)) return AjaxRequestFailure();

            var user = await UserManager.GetUserAsync(HttpContext.User);
            var result = new AddOrSwapVoteForFeedEntry(Configuration.Value)
            {
                IsPositive = isUpvote,
                VotedEntryId = votedEntryId,
                VoterId = user.Id
            }.Execute();

            if (!result.WasSuccessful) return AjaxRequestFailure();

            return new JsonResult(
                new MakeVoteResultViewModel
                {
                    NewVoteBalance = result.Output.VotesBalance,
                    Upvote = isUpvote,
                    VotedEntry = votedEntryId
                });
        }
    }
}

src/SimpleFeed.Web/Views/Feed/AddExternalLinkForm.cshtml
@model SimpleFeed.Models.FeedViewModels.AddExternalLinkViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Add external content</h2>

@using (Html.BeginForm("AddExternalLink", "Feed", null, FormMethod.Post, true, new { id = "external-link-form" }))
{
    <div>
        <div>
            <p>Title:</p>
            <input type="text" asp-for="Title"/>
            <p>Description:</p>
            <input type="text" asp-for="Description"/>
            <p>URL:</p>
            <input type="text" asp-for="LinkAddress"/>
        </div>
    </div>
    <div>
        <div>
            <button id="external-link-submit" type="submit" class="reversed" value="Add">Add</button>
        </div>
    </div>

    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded",
            function() {
                    document.getElementById('external-link-form').addEventListener('submit', function(e) {
                        $.ajax({
                            async: true,
                            url: this.action,
                            type: this.method,
                            dataType: "json",
                            data: $(this).serialize(),
                            success: function(result) {
                                if (!result.success) return;
                                window.location = '/Feed/GetEntry?entryId=' + result.entryId;
                            }
                        });
                        e.preventDefault();
                        showLoader('Generating screenshot...');
                    });
            });
    </script>
}

src/SimpleFeed.Web/Views/Feed/AddFeedEntryForm.cshtml
@model dynamic

@{
    Layout = "_Layout";
}

<h1>What will you share today?</h1>

<div id="choose-entry-container">
    <div class="choose-entry left">
        <a asp-controller="Feed" asp-action="AddUploadedImageForm">
            <img src="~/images/icons/ico-uploaded_image_large.png"/>
            <div class="choose-entry-text">An uploaded image...</div>
        </a>
    </div>
    <div class="choose-entry right">
        <a asp-controller="Feed" asp-action="AddExternalLinkForm">
            <img src="~/images/icons/ico-external_link_large.png" />
            <div class="choose-entry-text">An external link...</div>
        </a>
    </div> 
</div>

src/SimpleFeed.Web/Views/Feed/AddUploadedImageForm.cshtml
@model SimpleFeed.Models.FeedViewModels.AddUploadedImageViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Add image content</h2>

<form method="post" enctype="multipart/form-data" asp-controller="Feed" asp-action="AddUploadedImage">
    <div>
        <div>
            <p>Title:</p>
            <input type="text" asp-for="Title" />
            <p>Description:</p>
            <input type="text" asp-for="Description" />
        </div>
        <div>
            <p>Image to upload:</p>
            <input type="file" asp-for="Image"/>
        </div>
    </div>
    <div>
        <div>
            <button class="reversed" type="submit" value="Add">Add</button>
        </div>
    </div>
</form>

src/SimpleFeed.Web/Views/Feed/EditFeedEntry.cshtml
@model SimpleFeed.Core.FeedEntries.Base.FeedEntryBase

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Update feed entry</h2>

<form method="post" asp-controller="Feed" asp-action="UpdateFeedEntry">
    <div>
        <div>
            <input type="hidden" asp-for="Id"/>
            <p>Title:</p>
            <input type="text" asp-for="Title"/>
            <p>Description:</p>
            <input type="text" asp-for="Description"/>
        </div>
    </div>
    <div>
        <div>
            <button class="reversed" type="submit" value="Update">Update</button>
        </div>
    </div>
</form>

src/SimpleFeed.Web/Views/Feed/ExternalLinkFeedEntry.cshtml
@model SimpleFeed.Core.FeedEntries.ExternalLinkFeedEntry

ExternalLinkFeedEntry

src/SimpleFeed.Web/Views/Feed/GetEntry.cshtml
@using Microsoft.AspNetCore.Http
@using SimpleFeed.Core.FeedEntries
@using SimpleFeed.Core.User
@using SimpleFeed.HtmlHelpers
@model SimpleFeed.Data.OperationResults.ModelWithCreator<SimpleFeed.Core.FeedEntries.Base.FeedEntryBase>
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager

<div class="feed-entry">
    <div class="feed-entry-createdby">
        <div class="feed-entry-author">
            <a href="@Url.Action("GetUser", "User", new { userId = @Model.Creator.Id })">
                <img src="/images/user_default.png" />
                @Model.Creator.UserName
            </a>
        </div>
        <time class="timeago" datetime="@Model.Model.CreationDate.ToString("s", System.Globalization.CultureInfo.InvariantCulture)">
            @Model.Model.CreationDate.ToString("d")
        </time>
    </div>

    @Html.FeedEntryPartialFor(Model.Model)

    <div class="feed-entry-title">
        <div class="feed-entry-votes-wrapper">
            @using (Html.BeginForm("MakeVoteForFeedEntry", "Vote", new { votedEntryId = @Model.Model.Id, isUpvote = true },
                FormMethod.Post, true, new { id = $"upvote-{ Model.Model.Id }" }))
            {
                <div class="vote-img-wrapper">
                    <button type="submit">
                        <img src="/images/icons/ico-upvote.png">
                    </button>
                </div>
            }
            <div id="votescount-@Model.Model.Id" class="feed-entry-votescount">
                <span>@Model.Model.VotesBalance</span>
            </div>
            @using (Html.BeginForm("MakeVoteForFeedEntry", "Vote", new { votedEntryId = @Model.Model.Id, isUpvote = false },
                FormMethod.Post, true, new { id = $"downvote-{Model.Model.Id}" }))
            {
                <div class="vote-img-wrapper">
                    <button type="submit">
                        <img src="/images/icons/ico-downvote.png">
                    </button>
                </div>
            }
        </div>
        <a href="@Url.Action("GetEntry", new {entryId = Model.Model.Id})">@Model.Model.Title</a>
    </div>
    @if (Model.Model is UploadedImageFeedEntry)
    {
        <div class="feed-entry-type">
            <img src="~/images/icons/ico-uploaded_image.png" />
            <span>Uploaded image</span>
        </div>
    }
    else if (Model.Model is ExternalLinkFeedEntry)
    {
        <div class="feed-entry-type">
            <img src="~/images/icons/ico-external_link.png" />
            <span>External link</span>
        </div>
    }
    

    @if (SignInManager.IsSignedIn(User) && Model.Creator.Id.Equals(UserManager.GetUserAsync(User).Result.Id))
    {
        <div class="feed-entry-author-bar">
            @Html.ActionLink("Delete", "DeleteFeedEntry", new { entryId = Model.Model.Id }, new { Class = "right" })
            @Html.ActionLink("Update", "EditFeedEntry", new { entryId = Model.Model.Id }, new { Class = "right" })
        </div>
    }

    <div class="feed-entry-desc">
        @Model.Model.Description
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded",
        function() {
            wireSubmitVote("@Model.Model.Id.ToString()", true);
            wireSubmitVote("@Model.Model.Id.ToString()", false);
            $("time.timeago").timeago();
        });
</script>

src/SimpleFeed.Web/Views/Feed/Index.cshtml
@using SimpleFeed.Core.FeedEntries.Base
@using SimpleFeed.Data.OperationResults
@model PersistenceOperationResult<PaginatedResult<ModelWithCreator<FeedEntryBase>>>

@{
    Layout = "_Layout";
}

@{
    if (!Model.WasSuccessful)
    {
        <p>Whoops, something went wrong!</p>
    }
    else
    {
        foreach (var result in Model.Output.Result)
        {
            @Html.Partial("_FeedIndexElementPartial", result)
        }
    }
}

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded",
        function() {
            $("time.timeago").timeago();
        });
</script>

src/SimpleFeed.Web/Views/Feed/TopTen.cshtml
@model SimpleFeed.Data.OperationResults.PersistenceOperationResult<System.Collections.Generic.ICollection<SimpleFeed.Data.OperationResults.ModelWithCreator<SimpleFeed.Core.FeedEntries.Base.FeedEntryBase>>>

@{
    Layout = "_Layout";
}

<div id="top-ten-header">
    <div id="top-ten-img">
        <img src="~/images/icons/ico-top-ten.png" />
    </div>
    <h1>
        Top 10 entries
    </h1>
    <div id="top-ten-small">By votes count</div>
</div>

@{
    if (!Model.WasSuccessful)
    {
        <p>Whoops, something went wrong!</p>
    }
    else
    {
        foreach (var result in Model.Output)
        {
            @Html.Partial("_FeedIndexElementPartial", result)
        }
    }
}

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded",
        function() {
            $("time.timeago").timeago();
        });
</script>

src/SimpleFeed.Web/Views/Feed/UploadedImageFeedEntry.cshtml
@model SimpleFeed.Core.FeedEntries.UploadedImageFeedEntry

<img src="~/@Model.RelativeFilePath" />

src/SimpleFeed.Web/Views/Feed/_ExternalLinkFeedEntryPartial.cshtml
@using SimpleFeed.Data.Configuration
@model SimpleFeed.Core.FeedEntries.ExternalLinkFeedEntry
@inject IPersistenceConfiguration Configuration

<img src="@Configuration.GetRelativePathForUrlSnapshot(Model)"/>
<div class="external-link-url">
    <a href="@Model.LinkAddress">@Model.LinkAddress</a>
</div>

src/SimpleFeed.Web/Views/Feed/_FeedIndexElementPartial.cshtml
@using SimpleFeed.Core.FeedEntries
@using SimpleFeed.HtmlHelpers
@model SimpleFeed.Data.OperationResults.ModelWithCreator<SimpleFeed.Core.FeedEntries.Base.FeedEntryBase>

<div class="feed-entry">
    <div class="feed-entry-createdby">
        <div class="feed-entry-author">
            <a href="@Url.Action("GetUser", "User", new { userId = @Model.Creator.Id })">
                <img src="/images/user_default.png"/> 
                @Model.Creator.UserName
            </a>
        </div>
        <time class="timeago" datetime="@Model.Model.CreationDate.ToString("s", System.Globalization.CultureInfo.InvariantCulture)">
            @Model.Model.CreationDate.ToString("d")
        </time>
    </div>

    @Html.FeedEntryPartialFor(Model.Model)

    <div class="feed-entry-title">
        <div class="feed-entry-votes-wrapper">
            @using (Html.BeginForm("MakeVoteForFeedEntry", "Vote", new { votedEntryId = @Model.Model.Id, isUpvote = true }, 
                FormMethod.Post, true, new { id = $"upvote-{ Model.Model.Id }" }))
            {
                <div class="vote-img-wrapper">
                    <button type="submit">
                        <img src="/images/icons/ico-upvote.png">
                    </button>
                </div>
            }
            <div id="votescount-@Model.Model.Id" class="feed-entry-votescount">
                <span>@Model.Model.VotesBalance</span>
            </div>
            @using (Html.BeginForm("MakeVoteForFeedEntry", "Vote", new {votedEntryId = @Model.Model.Id, isUpvote = false},
                FormMethod.Post, true, new {id = $"downvote-{Model.Model.Id}"}))
            {
                <div class="vote-img-wrapper">
                    <button type="submit">
                        <img src="/images/icons/ico-downvote.png">
                    </button>
                </div>
            }
        </div>
        <a href="@Url.Action("GetEntry", new {entryId = Model.Model.Id})">@Model.Model.Title</a>
    </div>
    @if (Model.Model is UploadedImageFeedEntry)
    {
        <div class="feed-entry-type">
            <img src="~/images/icons/ico-uploaded_image.png"/>
            <span>Uploaded image</span>
        </div>
    }
    else if (Model.Model is ExternalLinkFeedEntry)
    {
        <div class="feed-entry-type">
            <img src="~/images/icons/ico-external_link.png" />
            <span>External link</span>
        </div>
    }
    <div class="feed-entry-desc">
        @Model.Model.Description
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded",
        function() {
            wireSubmitVote("@Model.Model.Id.ToString()", true);
            wireSubmitVote("@Model.Model.Id.ToString()", false);
        });
</script>

src/SimpleFeed.Web/Views/Feed/_UploadedImageFeedEntryPartial.cshtml
@model SimpleFeed.Core.FeedEntries.UploadedImageFeedEntry

<img class="uploaded-image-entry" src="~/@Model.RelativeFilePath" />